# Generated by Django 4.2 on 2023-10-22 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=50)),
                ('education', models.CharField(choices=[('physician', 'physician'), ('nurse', 'nurse'), ('physician assistant', 'physician assistant'), ('pharmacist', 'pharmacist'), ('PhD', 'PhD'), ('student', 'student'), ('other', 'other')], max_length=50)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('confirmed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('order', models.AutoField(primary_key=True, serialize=False)),
                ('seat_number', models.CharField(max_length=5)),
                ('assigned_to', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='arabspineapp.attendee')),
            ],
        ),
    ]
